services:
  db:
    image: postgres:15-alpine
    container_name: anime-catalog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: animecatalog
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: